review template module code
MagnusHJensen/ScalableTeaching pull request #6
Opened 2024-02-20 20:04 UTC by MagnusHJensen

## What kind of change does this PR introduce?

Reviews the template code.
Pushes the view code for the `pushes` section inside a task next to the Template module.
Also makes the controller next to the module handle the data requested from the view, which fetches all the recent pushes.

## What is the current behavior?

The page should behave the same.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

2024-02-27 10:38 UTC, mcamp commented on app/Models/Task.php
> +                'gitlab_project_id'        => $project['id'],
Is this going to affect something to the current courses/tasks in the system?

2024-02-27 10:39 UTC, mcamp commented
What is exactly a template code?

2024-02-28 07:49 UTC, MagnusHJensen commented on app/Models/Task.php
> +                'gitlab_project_id'        => $project['id'],
The column name is changed by a migration, so it should convert nicely.

2024-02-28 07:49 UTC, MagnusHJensen commented
> w code for the `pushes` secti

Code related to the Template module. That's bad wording from my side.

2024-03-02 14:31 UTC, MagnusHJensen commented
Converted to draft, since It now requires #8, to correctly verify the pushes tab is working.

2024-03-26 20:20 UTC, mcamp requested changes

2024-03-26 20:20 UTC, mcamp commented on app/Models/Task.php
> +                'gitlab_project_id'        => $project['id'],
But, is it necessary to change the name? what is the reason behind it?

2024-03-28 09:52 UTC, MagnusHJensen commented on app/Models/Task.php
> +                'gitlab_project_id'        => $project['id'],
Simply for clarity, it was super confusing, since a field `project_id` on `Project` class, would indicate to any reader, it's the ID for a related project, which it's not . It's the GitHub project.

2024-03-29 09:21 UTC, merged