Chore/review subtasks module
MagnusHJensen/ScalableTeaching pull request #7
Opened 2024-03-01 23:58 UTC by MagnusHJensen

## Requires: #6 

## What kind of change does this PR introduce?

Bug fix, feature, docs update, ...

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

2024-03-26 20:19 UTC, mcamp requested changes

2024-03-26 20:19 UTC, mcamp commented on app/Exports/SubtaskCompletionExport.php
> +        return Project::query()->claimed()->where("task_id", $this->task->id)->with("subTasks");
Why was this change necessary?

2024-03-26 20:19 UTC, mcamp commented on app/Listeners/GitLab/Project/RegisterWebhook.php
> +            $webhookUrl = 'https://scalableteaching.sdu.dk/api/reporter';
This hook should be part of the env file. That way, we avoid he if clause here.

2024-03-29 09:22 UTC, mcamp commented
Review comments and conflicts (sorry for accepting super late the last pull request)

2024-04-10 16:21 UTC, MagnusHJensen commented on app/Exports/SubtaskCompletionExport.php
> +        return Project::query()->claimed()->where("task_id", $this->task->id)->with("subTasks");
It was an attempt to get better type safety, but no luck.
Forgot to change it back.

2024-04-10 16:29 UTC, MagnusHJensen commented on app/Exports/SubtaskCompletionExport.php
> +        return Project::query()->claimed()->where("task_id", $this->task->id)->with("subTasks");
I now remember it was a type error from larastan.

2024-04-10 16:30 UTC, MagnusHJensen commented on app/Listeners/GitLab/Project/RegisterWebhook.php
> +            $webhookUrl = 'https://scalableteaching.sdu.dk/api/reporter';
Made it part of the env, and updated readme to reflect these changes (also the part about ngrok instead of valet)

2024-05-17 11:53 UTC, mcamp commented
Sorry for the delay on the pull requests which results in this branch being with conflicts, can you check it?

2024-05-21 07:05 UTC, MagnusHJensen commented
> Sorry for the delay on the pull requests which results in this branch being with conflicts, can you check it?

Should be good now!

2024-05-23 14:31 UTC, merged